var base_armory_level = {
  level_map: [
    21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 21, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 21, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 21, 21, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 21, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 21, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 21, 21, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 21, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    21, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 21, 21, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 21, 21, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
  ],
  tile_map: [
    10, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 8, 27, 4, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 26, 27, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 26, 27, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 27, 3, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 27, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 26, 27, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 27, 3, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 27, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    26, 27, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 27, 3, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 26, 27, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    26, 28, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 29,
  ],
  starting_ammo: 0,
  default_object_config: {
    direction: 0,
    orientation: "vertical",
    type: "",
    state: "moving",
    position: {
      x: 0,
      y: 0,
    },
    array_index: 0,
  },
  enemies: [],
  hazards: [],
  walls: [
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 6,
        y: 7,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 10,
        y: 25,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 8,
        y: 39,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 11,
        y: 51,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 7,
        y: 68,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 7,
        y: 85,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 2,
        y: 109,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 12,
        y: 119,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 10,
        y: 133,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 3,
        y: 153,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 2,
        y: 175,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 7,
        y: 188,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 9,
        y: 199,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 24,
        y: 200,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 43,
        y: 199,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 62,
        y: 199,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 104,
        y: 199,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 82,
        y: 201,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 70,
        y: 201,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 131,
        y: 200,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 170,
        y: 201,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 219,
        y: 205,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 112,
        y: 200,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 151,
        y: 201,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 231,
        y: 202,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 246,
        y: 203,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 197,
        y: 200,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 182,
        y: 200,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 246,
        y: 188,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 250,
        y: 168,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 251,
        y: 148,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 250,
        y: 122,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 249,
        y: 134,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 250,
        y: 109,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 247,
        y: 86,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 248,
        y: 69,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 248,
        y: 50,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 249,
        y: 36,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 249,
        y: 18,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 245,
        y: 5,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 229,
        y: 4,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 215,
        y: 6,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 201,
        y: 5,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 180,
        y: 6,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 160,
        y: 7,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 147,
        y: 6,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 129,
        y: 8,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 117,
        y: 9,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 104,
        y: 9,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 91,
        y: 9,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 80,
        y: 10,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 65,
        y: 10,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 49,
        y: 8,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 33,
        y: 8,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 24,
        y: 8,
      },
    },
    {
      direction: 0,
      orientation: "vertical",
      type: "collider",
      state: "moving",
      position: {
        x: 71,
        y: 199,
      },
    },
  ],
  shots: [],
  name: "",
  tileset: armory_tileset,
  song: "armory_music",
};

const ARMORY_LEVELS = [
  {
    level_map: [
      21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 21, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 1, 4, 4, 21, 21, 0, 0, 0, 20, 0, 0, 0, 0, 0, 0, 0, 1, 4, 4, 21, 21, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 4, 4, 21, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 1, 1, 21, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 21, 21,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 21, 21, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 21, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 21,
      21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 21, 21, 0, 0, 2, 0, 0, 0, 0,
      0, 0, 0, 0, 1, 0, 3, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
      21, 21, 21, 21,
    ],
    tile_map: [
      10, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 8, 27, 4, 2,
      2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 26, 27, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 26, 27, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 27, 3,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 27, 3, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 26, 27, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 27,
      3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 27, 3, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 26, 27, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26,
      27, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 27, 3, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 26, 28, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
      14, 14, 14, 29,
    ],
    starting_ammo: 0,
    default_object_config: {
      direction: 0,
      orientation: "vertical",
      type: "",
      state: "moving",
      position: {
        x: 0,
        y: 0,
      },
      array_index: 0,
    },
    enemies: [
      {
        direction: 0,
        orientation: "vertical",
        type: "flyer",
        state: "moving",
        position: {
          x: 74,
          y: 53,
        },
        array_index: 52,
      },
    ],
    hazards: [],
    walls: [
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 6,
          y: 7,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 10,
          y: 25,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 8,
          y: 39,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 11,
          y: 51,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 7,
          y: 68,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 7,
          y: 85,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 2,
          y: 109,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 12,
          y: 119,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 10,
          y: 133,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 3,
          y: 153,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 2,
          y: 175,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 7,
          y: 188,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 9,
          y: 199,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 24,
          y: 200,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 43,
          y: 199,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 62,
          y: 199,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 104,
          y: 199,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 82,
          y: 201,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 70,
          y: 201,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 131,
          y: 200,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 170,
          y: 201,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 219,
          y: 205,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 112,
          y: 200,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 151,
          y: 201,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 231,
          y: 202,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 246,
          y: 203,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 197,
          y: 200,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 182,
          y: 200,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 246,
          y: 188,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 250,
          y: 168,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 251,
          y: 148,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 250,
          y: 122,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 249,
          y: 134,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 250,
          y: 109,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 247,
          y: 86,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 248,
          y: 69,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 248,
          y: 50,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 249,
          y: 36,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 249,
          y: 18,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 245,
          y: 5,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 229,
          y: 4,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 215,
          y: 6,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 201,
          y: 5,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 180,
          y: 6,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 160,
          y: 7,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 147,
          y: 6,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 129,
          y: 8,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 117,
          y: 9,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 104,
          y: 9,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 91,
          y: 9,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 80,
          y: 10,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 65,
          y: 10,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 49,
          y: 8,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 33,
          y: 8,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 24,
          y: 8,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 71,
          y: 199,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "normal_wall",
        state: "moving",
        position: {
          x: 201,
          y: 183,
        },
        array_index: 188,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "normal_wall",
        state: "moving",
        position: {
          x: 216,
          y: 166,
        },
        array_index: 173,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "normal_wall",
        state: "moving",
        position: {
          x: 231,
          y: 151,
        },
        array_index: 158,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "normal_wall",
        state: "moving",
        position: {
          x: 206,
          y: 77,
        },
        array_index: 76,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "normal_wall",
        state: "moving",
        position: {
          x: 219,
          y: 86,
        },
        array_index: 93,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "normal_wall",
        state: "moving",
        position: {
          x: 197,
          y: 54,
        },
        array_index: 60,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "normal_wall",
        state: "moving",
        position: {
          x: 196,
          y: 41,
        },
        array_index: 44,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "normal_wall",
        state: "moving",
        position: {
          x: 232,
          y: 24,
        },
        array_index: 30,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "normal_wall",
        state: "moving",
        position: {
          x: 216,
          y: 24,
        },
        array_index: 29,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "normal_wall",
        state: "moving",
        position: {
          x: 232,
          y: 85,
        },
        array_index: 94,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "normal_wall",
        state: "moving",
        position: {
          x: 239,
          y: 91,
        },
        array_index: 94,
      },
    ],
    shots: [
      {
        direction: 0,
        orientation: "vertical",
        type: "normal_shot",
        state: "moving",
        position: {
          x: 221,
          y: 50,
        },
        array_index: 61,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "normal_shot",
        state: "moving",
        position: {
          x: 235,
          y: 59,
        },
        array_index: 62,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "normal_shot",
        state: "moving",
        position: {
          x: 220,
          y: 72,
        },
        array_index: 77,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "normal_shot",
        state: "moving",
        position: {
          x: 232,
          y: 72,
        },
        array_index: 78,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "normal_shot",
        state: "moving",
        position: {
          x: 218,
          y: 42,
        },
        array_index: 45,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "normal_shot",
        state: "moving",
        position: {
          x: 229,
          y: 39,
        },
        array_index: 46,
      },
    ],
    name: "2-3",
    tileset: armory_tileset,
    song: "armory_music",
  },
  {
    level_map: [
      21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 21, 21, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0,
      0, 0, 0, 0, 21, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 21, 21, 0,
      20, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 20, 0, 21, 21, 0, 0, 21, 0, 0,
      0, 0, 0, 0, 0, 0, 21, 0, 0, 21, 21, 0, 0, 21, 0, 0, 0, 0, 0, 0, 0, 0, 21,
      0, 0, 21, 21, 0, 0, 21, 0, 0, 0, 0, 0, 0, 0, 0, 21, 0, 0, 21, 21, 20, 0,
      21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 0, 20, 21, 21, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 21, 21, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0,
      21, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 21, 21, 21, 21, 21, 21,
      21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
    ],
    tile_map: [
      10, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 8, 27, 4, 2,
      2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 26, 27, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 26, 27, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 27, 3,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 27, 3, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 26, 27, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 27,
      3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 27, 3, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 26, 27, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26,
      27, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 27, 3, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 26, 28, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
      14, 14, 14, 29,
    ],
    starting_ammo: 0,
    default_object_config: {
      direction: 0,
      orientation: "vertical",
      type: "",
      state: "moving",
      position: {
        x: 0,
        y: 0,
      },
      array_index: 0,
    },
    enemies: [
      {
        direction: 90,
        orientation: "vertical",
        type: "flyer",
        state: "moving",
        position: {
          x: 218,
          y: 69,
        },
        array_index: 77,
      },
      {
        direction: 270,
        orientation: "vertical",
        type: "flyer",
        state: "moving",
        position: {
          x: 232,
          y: 132,
        },
        array_index: 142,
      },
      {
        direction: 90,
        orientation: "vertical",
        type: "flyer",
        state: "moving",
        position: {
          x: 39,
          y: 69,
        },
        array_index: 66,
      },
      {
        direction: 270,
        orientation: "vertical",
        type: "flyer",
        state: "moving",
        position: {
          x: 24,
          y: 136,
        },
        array_index: 129,
      },
    ],
    hazards: [],
    walls: [
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 6,
          y: 7,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 10,
          y: 25,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 8,
          y: 39,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 11,
          y: 51,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 7,
          y: 68,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 7,
          y: 85,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 2,
          y: 109,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 12,
          y: 119,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 10,
          y: 133,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 3,
          y: 153,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 2,
          y: 175,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 7,
          y: 188,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 9,
          y: 199,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 24,
          y: 200,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 43,
          y: 199,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 62,
          y: 199,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 104,
          y: 199,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 82,
          y: 201,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 70,
          y: 201,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 131,
          y: 200,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 170,
          y: 201,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 219,
          y: 205,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 112,
          y: 200,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 151,
          y: 201,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 231,
          y: 202,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 246,
          y: 203,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 197,
          y: 200,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 182,
          y: 200,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 246,
          y: 188,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 250,
          y: 168,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 251,
          y: 148,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 250,
          y: 122,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 249,
          y: 134,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 250,
          y: 109,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 247,
          y: 86,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 248,
          y: 69,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 248,
          y: 50,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 249,
          y: 36,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 249,
          y: 18,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 245,
          y: 5,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 229,
          y: 4,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 215,
          y: 6,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 201,
          y: 5,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 180,
          y: 6,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 160,
          y: 7,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 147,
          y: 6,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 129,
          y: 8,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 117,
          y: 9,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 104,
          y: 9,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 91,
          y: 9,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 80,
          y: 10,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 65,
          y: 10,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 49,
          y: 8,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 33,
          y: 8,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 24,
          y: 8,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 71,
          y: 199,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 57,
          y: 71,
        },
        array_index: 67,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 55,
          y: 88,
        },
        array_index: 83,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 58,
          y: 100,
        },
        array_index: 99,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 56,
          y: 119,
        },
        array_index: 115,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 57,
          y: 134,
        },
        array_index: 131,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 74,
          y: 135,
        },
        array_index: 132,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 90,
          y: 137,
        },
        array_index: 133,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 104,
          y: 136,
        },
        array_index: 134,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 75,
          y: 71,
        },
        array_index: 68,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 199,
          y: 72,
        },
        array_index: 76,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 200,
          y: 88,
        },
        array_index: 92,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 200,
          y: 108,
        },
        array_index: 108,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 201,
          y: 122,
        },
        array_index: 124,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 199,
          y: 137,
        },
        array_index: 140,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 183,
          y: 135,
        },
        array_index: 139,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 179,
          y: 70,
        },
        array_index: 75,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 165,
          y: 72,
        },
        array_index: 74,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 152,
          y: 72,
        },
        array_index: 73,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 139,
          y: 71,
        },
        array_index: 72,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 123,
          y: 70,
        },
        array_index: 71,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 103,
          y: 71,
        },
        array_index: 70,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 86,
          y: 70,
        },
        array_index: 69,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 119,
          y: 135,
        },
        array_index: 135,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 133,
          y: 134,
        },
        array_index: 136,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 155,
          y: 137,
        },
        array_index: 137,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 167,
          y: 137,
        },
        array_index: 138,
      },
    ],
    shots: [],
    name: "",
    tileset: armory_tileset,
    song: "armory_music",
  },
  {
    level_map: [
      21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 4, 4,
      4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 21, 21, 0, 0, 0, 20, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 3, 21, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 21, 21, 0,
      0, 20, 0, 0, 0, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 0, 0, 0, 0, 0, 0,
      21, 0, 0, 0, 0, 0, 0, 0, 21, 21, 0, 0, 0, 0, 0, 0, 21, 0, 0, 0, 0, 0, 0,
      0, 21, 21, 0, 0, 0, 0, 0, 0, 21, 0, 0, 0, 0, 0, 0, 0, 21, 21, 0, 0, 0, 0,
      0, 0, 21, 0, 0, 0, 0, 0, 0, 0, 21, 21, 0, 0, 0, 0, 0, 0, 21, 21, 21, 21,
      21, 21, 21, 21, 21, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 21, 21,
      4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 21, 21, 21, 21, 21, 21, 21, 21,
      21, 21, 21, 21, 21, 21, 21, 21, 21,
    ],
    tile_map: [
      10, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 8, 27, 4, 2,
      2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 26, 27, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 26, 27, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 27, 3,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 27, 3, 0, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 26, 27, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 27,
      3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 27, 3, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 26, 27, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26,
      27, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 27, 3, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 26, 28, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
      14, 14, 14, 29,
    ],
    starting_ammo: 0,
    default_object_config: {
      direction: 0,
      orientation: "vertical",
      type: "",
      state: "moving",
      position: {
        x: 0,
        y: 0,
      },
      array_index: 0,
    },
    enemies: [
      {
        direction: 0,
        orientation: "vertical",
        type: "flyer",
        state: "moving",
        position: {
          x: 74,
          y: 39,
        },
        array_index: 36,
      },
      {
        direction: 90,
        orientation: "vertical",
        type: "flyer",
        state: "moving",
        position: {
          x: 53,
          y: 78,
        },
        array_index: 67,
      },
    ],
    hazards: [],
    walls: [
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 6,
          y: 7,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 10,
          y: 25,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 8,
          y: 39,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 11,
          y: 51,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 7,
          y: 68,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 7,
          y: 85,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 2,
          y: 109,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 12,
          y: 119,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 10,
          y: 133,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 3,
          y: 153,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 2,
          y: 175,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 7,
          y: 188,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 9,
          y: 199,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 24,
          y: 200,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 43,
          y: 199,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 62,
          y: 199,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 104,
          y: 199,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 82,
          y: 201,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 70,
          y: 201,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 131,
          y: 200,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 170,
          y: 201,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 219,
          y: 205,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 112,
          y: 200,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 151,
          y: 201,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 231,
          y: 202,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 246,
          y: 203,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 197,
          y: 200,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 182,
          y: 200,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 246,
          y: 188,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 250,
          y: 168,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 251,
          y: 148,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 250,
          y: 122,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 249,
          y: 134,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 250,
          y: 109,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 247,
          y: 86,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 248,
          y: 69,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 248,
          y: 50,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 249,
          y: 36,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 249,
          y: 18,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 245,
          y: 5,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 229,
          y: 4,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 215,
          y: 6,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 201,
          y: 5,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 180,
          y: 6,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 160,
          y: 7,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 147,
          y: 6,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 129,
          y: 8,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 117,
          y: 9,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 104,
          y: 9,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 91,
          y: 9,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 80,
          y: 10,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 65,
          y: 10,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 49,
          y: 8,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 33,
          y: 8,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 24,
          y: 8,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 71,
          y: 199,
        },
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 119,
          y: 77,
        },
        array_index: 71,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 120,
          y: 93,
        },
        array_index: 87,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 122,
          y: 103,
        },
        array_index: 103,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 120,
          y: 116,
        },
        array_index: 119,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 120,
          y: 130,
        },
        array_index: 135,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 120,
          y: 145,
        },
        array_index: 151,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 121,
          y: 158,
        },
        array_index: 151,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 141,
          y: 152,
        },
        array_index: 152,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 158,
          y: 152,
        },
        array_index: 153,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 177,
          y: 152,
        },
        array_index: 155,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 199,
          y: 152,
        },
        array_index: 156,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 230,
          y: 153,
        },
        array_index: 158,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 230,
          y: 153,
        },
        array_index: 158,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 230,
          y: 153,
        },
        array_index: 158,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 218,
          y: 152,
        },
        array_index: 157,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 217,
          y: 152,
        },
        array_index: 157,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 169,
          y: 148,
        },
        array_index: 154,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 138,
          y: 74,
        },
        array_index: 72,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 156,
          y: 73,
        },
        array_index: 73,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 175,
          y: 73,
        },
        array_index: 74,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 186,
          y: 74,
        },
        array_index: 75,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 201,
          y: 72,
        },
        array_index: 76,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 217,
          y: 73,
        },
        array_index: 77,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "collider",
        state: "moving",
        position: {
          x: 232,
          y: 72,
        },
        array_index: 78,
      },
    ],
    shots: [
      {
        direction: 0,
        orientation: "vertical",
        type: "normal_shot",
        state: "moving",
        position: {
          x: 31,
          y: 29,
        },
        array_index: 17,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "normal_shot",
        state: "moving",
        position: {
          x: 45,
          y: 27,
        },
        array_index: 18,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "normal_shot",
        state: "moving",
        position: {
          x: 53,
          y: 26,
        },
        array_index: 19,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "normal_shot",
        state: "moving",
        position: {
          x: 26,
          y: 187,
        },
        array_index: 177,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "normal_shot",
        state: "moving",
        position: {
          x: 39,
          y: 186,
        },
        array_index: 178,
      },
      {
        direction: 0,
        orientation: "vertical",
        type: "normal_shot",
        state: "moving",
        position: {
          x: 54,
          y: 184,
        },
        array_index: 179,
      },
    ],
    name: "2-1",
    tileset: armory_tileset,
    song: "armory_music",
  },
];
