dialogue = [
  [
    "Cyrus? Come in, Cyrus?",
    "Can you hear me?",
    "Wake up!",
    "Today’s the day you’re getting free, soldier.",
    "Got your attention now? Good.",
    "Look inside your cell. You see that red orb? ",
    "That’s what’s getting you out.",
    "It’s ammo for your new cannon arm.",
    "We reprogrammed a robot on the inside to place it in your cell during the night.",
    "I’m sure that little thing will get turned into scrap once the Metallics find out.",
    "Make sure you don’t end up the same.",
    "Alright, no more wasting time.",
    "Just grab that ammo and load up your weapon.",
    "There’s more littered around the facility.",
    "Over and out, Cyrus. We’ll see you soon. ",
  ],
  [
    "Come in, Cyrus. Come in.",
    "Congrats on making it this far, soldier.",
    "You’ve got a long way ahead, but help is on the way.",
    "We’ve sent an extraction team to the prison.",
    "If you can make it to the outside, we’ll have the best chance of getting you back home.",
    "As to how many pieces you’ll come back as is up to you.",
    "Stay careful out there. Word of your escape has spread and the Metallics are sure to send top security soon.",
    "Intel says that the reprogrammed bot is still on the loose, but it’s acting ... strange. Not what our programmers expected.",
    "Approach with caution.",
    "Over and out, Cyrus. Don’t do anything stupid.",
  ],
  // Processing sequence
  [
    "Cyrus?! Come in, Cyrus?!?!",
    "You need to get out of there now!",
    "We just got word from our technician’s ...",
    "That little robot .. ",
    "It resisted the reprogramming!",
    "It lead us on - it was all a trap ...",
    "You were just the bait to lure the extraction team.",
    "All of them - everyone - was taken down by ... that thing...",
    "We don’t know what it is.",
    "Whatever you do: Don’t try to fight it. Just don’t. ",
    "Run.",
    "Over and out, Cyr - *bzzzzzt*",
  ],
  [],
  [],
];
