const frames = {
  frames: {
    "idle-down": {
      frame: { x: 0, y: 25, w: 15, h: 25 },
      rotated: false,
      trimmed: false,
      spriteSourceSize: { x: 0, y: 0, w: 15, h: 25 },
      sourceSize: { w: 15, h: 25 },
    },
    "idle-left": {
      frame: { x: 34, y: 56, w: 18, h: 25 },
      rotated: false,
      trimmed: false,
      spriteSourceSize: { x: 0, y: 0, w: 18, h: 25 },
      sourceSize: { w: 18, h: 25 },
    },
    "idle-right": {
      frame: { x: 0, y: 81, w: 18, h: 25 },
      rotated: false,
      trimmed: false,
      spriteSourceSize: { x: 0, y: 0, w: 18, h: 25 },
      sourceSize: { w: 18, h: 25 },
    },
    "idle-up": {
      frame: { x: 15, y: 25, w: 15, h: 25 },
      rotated: false,
      trimmed: false,
      spriteSourceSize: { x: 0, y: 0, w: 15, h: 25 },
      sourceSize: { w: 15, h: 25 },
    },
    "shoot-down": {
      frame: { x: 30, y: 25, w: 15, h: 25 },
      rotated: false,
      trimmed: false,
      spriteSourceSize: { x: 0, y: 0, w: 15, h: 25 },
      sourceSize: { w: 15, h: 25 },
    },
    "shoot-left": {
      frame: { x: 18, y: 81, w: 18, h: 25 },
      rotated: false,
      trimmed: false,
      spriteSourceSize: { x: 0, y: 0, w: 18, h: 25 },
      sourceSize: { w: 18, h: 25 },
    },
    "shoot-right": {
      frame: { x: 36, y: 81, w: 18, h: 25 },
      rotated: false,
      trimmed: false,
      spriteSourceSize: { x: 0, y: 0, w: 18, h: 25 },
      sourceSize: { w: 18, h: 25 },
    },
    "shoot-up": {
      frame: { x: 45, y: 25, w: 15, h: 31 },
      rotated: false,
      trimmed: false,
      spriteSourceSize: { x: 0, y: 0, w: 15, h: 31 },
      sourceSize: { w: 15, h: 31 },
    },
    stance: {
      frame: { x: 36, y: 106, w: 21, h: 25 },
      rotated: false,
      trimmed: false,
      spriteSourceSize: { x: 0, y: 0, w: 21, h: 25 },
      sourceSize: { w: 21, h: 25 },
    },
    "walk-down-1": {
      frame: { x: 0, y: 0, w: 13, h: 25 },
      rotated: false,
      trimmed: false,
      spriteSourceSize: { x: 0, y: 0, w: 13, h: 25 },
      sourceSize: { w: 13, h: 25 },
    },
    "walk-down-2": {
      frame: { x: 13, y: 0, w: 13, h: 25 },
      rotated: false,
      trimmed: false,
      spriteSourceSize: { x: 0, y: 0, w: 13, h: 25 },
      sourceSize: { w: 13, h: 25 },
    },
    "walk-left-1": {
      frame: { x: 0, y: 56, w: 17, h: 25 },
      rotated: false,
      trimmed: false,
      spriteSourceSize: { x: 0, y: 0, w: 17, h: 25 },
      sourceSize: { w: 17, h: 25 },
    },
    "walk-left-2": {
      frame: { x: 0, y: 106, w: 18, h: 25 },
      rotated: false,
      trimmed: false,
      spriteSourceSize: { x: 0, y: 0, w: 18, h: 25 },
      sourceSize: { w: 18, h: 25 },
    },
    "walk-right-1": {
      frame: { x: 17, y: 56, w: 17, h: 25 },
      rotated: false,
      trimmed: false,
      spriteSourceSize: { x: 0, y: 0, w: 17, h: 25 },
      sourceSize: { w: 17, h: 25 },
    },
    "walk-right-2": {
      frame: { x: 18, y: 106, w: 18, h: 25 },
      rotated: false,
      trimmed: false,
      spriteSourceSize: { x: 0, y: 0, w: 18, h: 25 },
      sourceSize: { w: 18, h: 25 },
    },
    "walk-up-1": {
      frame: { x: 26, y: 0, w: 14, h: 25 },
      rotated: false,
      trimmed: false,
      spriteSourceSize: { x: 0, y: 0, w: 14, h: 25 },
      sourceSize: { w: 14, h: 25 },
    },
    "walk-up-2": {
      frame: { x: 40, y: 0, w: 14, h: 25 },
      rotated: false,
      trimmed: false,
      spriteSourceSize: { x: 0, y: 0, w: 14, h: 25 },
      sourceSize: { w: 14, h: 25 },
    },
  },
};
